### ISSUE TITLE
why not allow directive on field argument ?

### ISSUE THREAD

**Issue by Boyce-Lee** [graphql/graphql-spec#1061] opened 2023-11-15 07:39 UTC
in my work,  I use GQL As a well-defined DSL for BFF perpose to link backend data, like rpc / http / or other datasrouce.
directive on field argument is import feature for me.
what I want :
```graphql
query Demo(
   id: String
) {
     AInfo(
        id: $id @check(validate: "_ > 10")
     ) {
        name
    }

   BInfo(
      id: $id @check(validate: "_ > 20") @transfer(expr: "_ + 10")
   ) {
       name
  }
}
```

**Comment by glen-84** [comment] 2024-02-04 19:34
Duplicate of #931.

**Comment by benjie** [comment] 2024-02-19 11:01
This does indeed seem to be a duplicate; please add your use case to that thread :+1:

**Closed by benjie** 2024-02-19 11:01 UTC
